### ISSUE TITLE
Issue with react types with `render`

### ISSUE THREAD

**Issue by konsalex** [neo4j/cypher-editor#120]
### Description

Implementing this in Needle Codeblock and we face a react type issue:

```
TS2786: 'CypherEditor' cannot be used as a JSX component.   
Its instance type 'CypherEditor' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
Type 'React.ReactNode' is not assignable to type 'import(".../Neo4j/neo4j-design/node_modules/@types/react-table/node_modules/@types/react/index").ReactNode'.
Type '{}' is not assignable to type 'ReactNode'.
```

The types are `@types/react@17.0.52`. Maybe this is an inconsistency with react v18 provided types, not sure if other products are having an issue yet.

### Expected Behavior

Work out of the box for react v17.

### Can you propose a solution?

I can see Workspace, OpsManager and Console are still using v17, so we could consider fixing the types to the v17 for some time until products start using v18?

### Additional Information

For reproduction pull this commit: https://github.com/neo4j/neo4j-design/pull/496/commits/ccfc7beeadd91bfade8b0b132b5f36125fb20875 and then `yarn` to install packages and go to `CypherCodeblock.tsx`

**Comment by jharris4** [comment]
Huh interesting I had a look around at what React versions people are using the new editor with and it turns out, [neodash](https://github.com/neo4j-labs/neodash/blob/a8cf042ef8efbb693bd5cb7b734558c6577aa059/package.json) is on React `^17.0.2` and [cypher-workbench](https://github.com/Neo4jSolutions/cypher-workbench/blob/7ff28d196a322e06bf5ca82e4b7f44cc2eb5c2b4/ui/package.json) is on React `^16.9.0`.

I tried the repro steps you mentioned above, and did some digging, and I think there are somehow two versions of the react types installed in the `neo4j-design` repo, which has nothing to do with the cypher editor lol.

You can see the duplicate React package json files here after a `yarn install`:

`neo4j-design/node_modules/@types/react-table/node_modules/@types/react/package.json`:

```
{
    "name": "@types/react",
    "version": "18.0.26"
}
```

`neo4j-design/node_modules/types/react/package.json`:

```
{
    "name": "@types/react",
    "version": "17.0.52"
}
```

**Comment by konsalex** [comment]
All react versions can be seen here from `yarn why @types/react`:

```bash
├─ @mdx-js/react@npm:2.3.0 [cb2b6]
│  └─ @types/react@npm:18.0.28 (via npm:>=16)
│
├─ @neo4j-ndl/react@workspace:packages/react [d75d7]
│  └─ @types/react@npm:17.0.52 (via npm:17.0.52)
│
├─ @types/react-dom@npm:17.0.18
│  └─ @types/react@npm:17.0.53 (via npm:^17)
│
├─ @types/react-dom@npm:17.0.19
│  └─ @types/react@npm:17.0.53 (via npm:^17)
│
├─ @types/react-syntax-highlighter@npm:15.5.6
│  └─ @types/react@npm:18.0.28 (via npm:*)
│
├─ @types/react-table@npm:7.7.14
│  └─ @types/react@npm:18.0.28 (via npm:*)
│
└─ @types/react-transition-group@npm:4.4.5
   └─ @types/react@npm:18.0.28 (via npm:*)
```

I did some more testing, not sure how the typescript compiler is resolving the types for react, but somehow the transitive dependencies are messing up the compiler. Used `resolutions` field in root package.json of the monorepo, with `"@types/react": "^17.0.53"` and I can see the error is away now 🤔 

Will do a bit more testing and if issue comes up again will re-open! Thanks for taking a look @jharris4
